# Generated by Django 2.2 on 2020-07-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
